package com.xsloth.aku.db.hibernate;

// Generated 7/Set/2012 4:50:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LeagueRank generated by hbm2java
 */
@Entity
@Table(name = "league_rank", catalog = "aku")
public class LeagueRank implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private League league;
	private Rank rank;

	public LeagueRank() {
	}

	public LeagueRank(League league, Rank rank) {
		this.league = league;
		this.rank = rank;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_league", nullable = false)
	public League getLeague() {
		return this.league;
	}

	public void setLeague(League league) {
		this.league = league;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rank", nullable = false)
	public Rank getRank() {
		return this.rank;
	}

	public void setRank(Rank rank) {
		this.rank = rank;
	}

}
