package com.xsloth.aku.db.hibernate;

// Generated 7/Set/2012 4:50:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * League generated by hbm2java
 */
@Entity
@Table(name = "league", catalog = "aku")
public class League implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String league;
	private long leagueNumber;
	private Set<LeagueRank> leagueRanks = new HashSet<LeagueRank>(0);

	public League() {
	}

	public League(String league, long leagueNumber) {
		this.league = league;
		this.leagueNumber = leagueNumber;
	}

	public League(String league, long leagueNumber, Set<LeagueRank> leagueRanks) {
		this.league = league;
		this.leagueNumber = leagueNumber;
		this.leagueRanks = leagueRanks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "league", nullable = false, length = 250)
	public String getLeague() {
		return this.league;
	}

	public void setLeague(String league) {
		this.league = league;
	}

	@Column(name = "league_number", nullable = false)
	public long getLeagueNumber() {
		return this.leagueNumber;
	}

	public void setLeagueNumber(long leagueNumber) {
		this.leagueNumber = leagueNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "league")
	public Set<LeagueRank> getLeagueRanks() {
		return this.leagueRanks;
	}

	public void setLeagueRanks(Set<LeagueRank> leagueRanks) {
		this.leagueRanks = leagueRanks;
	}

}
