package com.xsloth.aku.db.hibernate;

// Generated 7/Set/2012 4:50:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "aku")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String nick;
	private String password;
	private String firstName;
	private String lastName;
	private String email;
	private Set<Rank> ranks = new HashSet<Rank>(0);
	private Set<Fight> fightsForOpponent = new HashSet<Fight>(0);
	private Set<Fight> fightsForIdUser = new HashSet<Fight>(0);

	public User() {
	}

	public User(String nick, String password, String firstName,
			String lastName, String email) {
		this.nick = nick;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}

	public User(String nick, String password, String firstName,
			String lastName, String email, Set<Rank> ranks,
			Set<Fight> fightsForOpponent, Set<Fight> fightsForIdUser) {
		this.nick = nick;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.ranks = ranks;
		this.fightsForOpponent = fightsForOpponent;
		this.fightsForIdUser = fightsForIdUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nick", nullable = false, length = 250)
	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", nullable = false, length = 250)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 250)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Rank> getRanks() {
		return this.ranks;
	}

	public void setRanks(Set<Rank> ranks) {
		this.ranks = ranks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByOpponent")
	public Set<Fight> getFightsForOpponent() {
		return this.fightsForOpponent;
	}

	public void setFightsForOpponent(Set<Fight> fightsForOpponent) {
		this.fightsForOpponent = fightsForOpponent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByIdUser")
	public Set<Fight> getFightsForIdUser() {
		return this.fightsForIdUser;
	}

	public void setFightsForIdUser(Set<Fight> fightsForIdUser) {
		this.fightsForIdUser = fightsForIdUser;
	}

}
